config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get 'home', to: 'home#index'

  resources :contents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user

  validates :title, :description, presence: true

  has_many :tag_contents, dependent: :destroy
  has_many :tags, through: :tag_contents
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: :user_id }

  has_many :tag_contents, dependent: :destroy
  has_many :contents, through: :tag_contents
end

app/models/tag_content.rb
class TagContent < ApplicationRecord
  belongs_to :tag
  belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contents
  has_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  def index
    @contents = current_user.contents

    tag_names = params[:tags]

    if tag_names.present?
      @contents = @contents.joins(:tags).where(tags: { name: tag_names }).distinct
    end
  end

  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
  end

  def new
    @content = Content.new
  end

  def create
    @content = current_user.contents.build(content_params)

    if @content.save
      associate_tags!

      redirect_to contents_path, notice: 'Content successfully created!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @content.update(content_params)
      associate_tags!

      redirect_to contents_path, notice: 'Content successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @content.destroy

    redirect_to contents_path, notice: 'Content successfully destroyed!'
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end

  def tags_params
    params.require(:content).permit(tags: [])[:tags].reject(&:blank?)
  end

  def content_params
    params.require(:content).permit(:title, :description)
  end

  def associate_tags!
    tags = tags_params.map do |tag_name|
      current_user.tags.where(name: tag_name).first_or_initialize
    end

    @content.tags = tags
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags_data = current_user.contents.joins(:tags).group('tags.name').count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contents/_form.html.erb
<% if content.errors.any? %>
  Errors: <%= content.errors.full_messages.join(', ') %>
  <BR>
  <BR>
<% end %>

<%= form_with(model: content, local: true) do |form| %>
  <div class='form-group'>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :tags %>
    <%= form.select :tags, options_for_select(current_user.tags.pluck(:name), content.tags.pluck(:name)), {}, { class: 'select2 form-control', multiple: 'multiple' } %>
  </div>

  <div class='actions'>
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Edit Content</h1>

<%= render 'form', content: @content %>

app/views/contents/index.html.erb
<%= link_to 'New Content', new_content_path %>

<h1>Contents</h1>

<%= form_tag(contents_path, method: :get) do %>
  <div class='form-group'>
    <%= label_tag :tags %>
    <%= select_tag 'tags[]', options_for_select(current_user.tags.pluck(:name), params[:tags]), class: 'select2 form-control', multiple: 'multiple' %>
  </div>

  <div class='actions'>
    <%= submit_tag 'Search', class: 'btn btn-primary' %>
  </div>
<% end %>

<BR>
<BR>

<% @contents.each do |content| %>
  <%= link_to 'Show', content_path(content) %>
  <%= link_to 'Edit', edit_content_path(content) %>
  <%= link_to 'Destroy', content_path(content), method: :delete, data: { confirm: 'Are you sure?' }  %>
  <strong>Title</strong>: <%= content.title %>
  <strong>Description</strong>: <%= content.description %>
  <strong>Tags</strong>: <%= content.tags.pluck(:name).join(', ') %>
  <BR>
<% end %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

app/views/contents/show.html.erb
<h1><%= @content.title %></h1>

<%= raw @markdown.render(@content.description) %>

app/views/home/index.html.erb
<h1>Cloud Tags</h1>

<% @tags_data.each do |tag_name, count| %>
  <% font_size = count * 20 %>

  <span style='font-size: <%= font_size > 70 ? 70 : font_size %>px'>
    <%= link_to tag_name, contents_path(tags: [tag_name]), style: 'text-decoration: none' %>
  </span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        <%= link_to 'Home', home_path %>
        <%= link_to 'Contents', contents_path %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% end %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>